apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: adminer
    spec:
      containers:
        - image: docker.io/adminer
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: adminer
          ports:
            - containerPort: 8080
              name: adminer
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 150m
              memory: 300mi
            requests:
              cpu: 100m
              memory: 12Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
